name: continous-integration

on:
  workflow_dispatch:       
  push:
    branches: [ "main" ]   
    paths: [ "input/**" ]  
  pull_request:
    branches: [ "main" ]
    paths: [ "input/**" ]
  
env:
  GH_TOKEN: ${{ github.token }}

jobs:    
  
  # ----------------------------------------------------------------------

  convert-files:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - run: gh release download wip --pattern 'xml2gmd' 
      - run: chmod +x xml2gmd
      - run: ./xml2gmd # xml-input gmd-output comments
      - run: rm xml2gmd 
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: generated output from xml2gmd
          #commit_user_name: converter[job]
          #commit_user_email: converter[job]@cascade.de
          #commit_author: converter[job]
          #commit_options: '--signoff'
  
  # ----------------------------------------------------------------------       
  
  tag-wip-rolling-release:
    runs-on: ubuntu-latest
    needs: convert-files
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "wip"
          message: "rolling: work in progress"
          force_push_tag: true
          
